### ISSUE TITLE
Bullet angle is wrong at very short distances/when looking down

### ISSUE THREAD

**Issue by LivingFray** [LivingFray/HellsingerVR#29]
Also need to check aim assist isn't causing any interference

**Comment by esvban** [comment]
I think I reproduced this bug here? https://www.youtube.com/watch?v=u1rbNJHo4kc&t=8s&ab_channel=esvban 

Does the game have built in aim assist? I tried googling it and one site said The Hounds have aim assist on beat, but i cant find any confirmation. How do you disable it?

**Comment by LivingFray** [comment]
That could be the cause, I believe there's an aim assist in the game. I currently change the bullet trajectory by calculating what the original bullet spread was based on the camera direction and applying that to the gun's direction, so it might be applying the aim assist which gets mistakenly detected as a bullet spread

**Comment by LivingFray** [comment]
Turns out part of the problem was there's a bunch of invisible triggers in the map that my code was mistakenly treating as solid when calculating bullet trajeectories. I've also patched aim assist to be always off to be on the safe side.
