### ISSUE TITLE
Setting left handed the health,ultimate, etc. ui in wrong position and mirrored

### ISSUE THREAD

**Issue by Hoshi82** [LivingFray/HellsingerVR#34]
First I was confused why I don't have any health indicator because the games was constantly telling me about it. Then I tried to turn my off-hand (left controller) and realized it's on the back of the hand and I have to turn my wrist to even see it. Also the ui is mirrored. For now have to set it to be right in front of me.

**Comment by LivingFray** [comment]
Fixed in 0.6.1
