### ISSUE TITLE
0.7 release - guns are semi transparent / faces seem inverted

### ISSUE THREAD

**Issue by esvban** [LivingFray/HellsingerVR#37]
after upgrading from 0.64 to 0.7, the guns are not rendering properly anymore. I just did an extract with replace all

Valve index
RTX 4090

let me know if you need any more detail

![image](https://user-images.githubusercontent.com/902108/216807913-e01f2de1-bf01-42b9-9451-f4a9e7a43804.png)

![image](https://user-images.githubusercontent.com/902108/216808084-102e0db9-506a-45d2-b7a9-50f279266984.png)

**Comment by LivingFray** [comment]
Oops, when reworking the rendering behind the scenes I forgot to re-adjust the near clip plane (distance from the camera at which things stop rendering). Fixed in 0.7.1
