### ISSUE TITLE
UI text elements are reversed sometimes

### ISSUE THREAD

**Issue by esvban** [LivingFray/HellsingerVR#38]
This is a minor issue, not game breaking or anything.

The hit streak counter seems to spin a few degrees each time you land a hit. This is kind of cool but also hard to read sometimes, lol.
The calibration menu text is also reversed.

**Comment by LivingFray** [comment]
Will be fixed in the next release. For some reason there's a handful of UI elements that calculate their position in world space while the rest are content to be moved around the world without issue
