### ISSUE TITLE
Can't switch to secondary (next) weapon when Paz is disabled

### ISSUE THREAD

**Issue by esvban** [LivingFray/HellsingerVR#39]
This scenario happens on certain torment challenges and the 2nd to last level, acheron, where you are unable to use paz. Only the previous weapon hotkey works and selects the sword (next weapon works once the sword is equipped). Next weapon doesn't work if the primary weapon is equipped.

**Comment by esvban** [comment]
i think the next / previous weapon bindings may have issues on any level with less than 4 weapons, actually. https://github.com/LivingFray/HellsingerVR/blob/master/HellsingerVR/Components/VRInputManager.cs#L247-L255 This is mostly torments, or the Acheron level. I think maybe a better scheme would be to have an input for swapping between primary and secondary, and another input for swapping between terminus and paz, if there's a way to tell what's currently equipped (primary or secondary). Or, rather than emulating the gamepad input, is there no way to switch the weapons by index directly?

**Comment by LivingFray** [comment]
Should be fixed now, I've updated the code to check which slot the desired weapon is (paz, terminus, primary, secondary) rather than assuming it based on index
